version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/user_db
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  usermanagement:
    build: .
    container_name: usermanagement-app

    depends_on:
      - postgres

    ports:
      - "1234:1234"

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/user_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data: