sonar.projectKey=harsha33215_UserManagement-jenkins
sonar.organization=harsha33215

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.host.url=https://sonarcloud.io