name: Spring Boot CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: user_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d user_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: setup java 17
        uses: actions/checkout@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Give execute permission to Maven Wrapper
        run: chmod +x mvnw


      - name: Build Project
        run: ./mvnw clean install

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar

